[package]
name = "pingall"
version = "0.1.2"
edition = "2018"
description = "Ping everything you can reach."
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.22"
structopt = "0.3"
tokio = { version = "1", features = ["macros", "process", "rt"] }
