[package]
name = "pingall"
version = "0.3.6"
edition = "2018"
description = "Ping everything you can reach."
license = "GPL-3.0-or-later"
repository = "https://github.com/Fierthraix/pingall"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.26"
pico-args = "0.5"
tokio = { version = "1", features = ["net", "process", "rt"] }
tiny-ping = "0.5"
